### ISSUE TITLE
Works for Diablo III but doesn't work with Overwatch?

### ISSUE THREAD

**Issue by Melodonic** [MartB/RETC#17]
dunno what more to say...

**Comment by MartB** [comment]
I have no time to test this with overwatch atm, but if there was some sort of change only related to overwatch i hope someone else can figure out what it was.

**Comment by MartB** [comment]
Just tested this again with a clean installation of retc.
(Downloaded setup and installed it)

It works flawlessly when ingame, genjis effects work while he sword swings and everything else seems to be fine too.

#closed

**Comment by Trilled** [comment]
i think its my keyboard maybe? i have the k55 you can only light up 3 sections not individual keys

**Comment by Trilled** [comment]
https://youtu.be/WqLNc0e1384

**Comment by Trilled** [comment]
im i doing everything correct?

**Comment by Trilled** [comment]
im sorry if im really annoying lol i really want this

**Comment by MartB** [comment]
You are doing everything correctly in this video.
But you are probably right it could be your keyboard yeah can you get me the server.log from the C:\Program Files\RETC folder?

**Comment by Trilled** [comment]
i think it’s because my keyboard keys aren’t individually lit up
