### ISSUE TITLE
Tried this with Fortnite and is got blocked by Battleeye

### ISSUE THREAD

**Issue by bulletfever409** [MartB/RETC#18]
As the title suggests I put the wrappers into Fortnite for the razer effects but Battleeye blocked the effects on startup.

**Comment by MartB** [comment]
Thats sad, but they probably check the dlls by signature/hash and i cant make it work under these circumstances. You can probably petition them into adding support for the CorsairSDK itself, but i doubt fortnite will ever work with my dlls.

Kind regards
MartB

**Comment by MartB** [comment]
closing as this will probably never change.
