### ISSUE TITLE
Quake Champions

### ISSUE THREAD

**Issue by Excessive12** [MartB/RETC#20]
Hey Guys

I can't get this working with Quake Champions?

Copied all the DLL files into the Quake Champions folder, no result :/

**Comment by MartB** [comment]
I dont have access to this game but i suppose the anticheat is blocking the dlls.

**Comment by MartB** [comment]
Can you check #22 and see if quake champions has a similar dll?
If it has try the stuff i wrote there.

**Comment by Excessive12** [comment]
Doesn’t seem to fix it for me, but I am almost definitely doing something wrong.

Do I need to have Razer Synapse installed?


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by MartB** [comment]
You only have to install razer synapse if you are using razer hardware, everything else should work just fine.
You do need corsair cue started though (or the newer iCue).

check `%programfiles%\RETC\server.log` for any error messages please.

**Comment by Excessive12** [comment]
Yeh I have iCUE.

That version seems to crash my PC.

Sent from outlook.com
________________________________
