### ISSUE TITLE
DOOM (2016)

### ISSUE THREAD

**Issue by PR91** [MartB/RETC#22]
Hello, I would like to congratulate the team for the amazing job supporting overweatch effects. I had a Razer Black Widow Chroma and now i own a k95 Platinum and it looks exactly the same. 
I was so blown away that I wanted to try out other titles that i knew were chroma compatible. 
So, I fired up DOOM and my mouse (Deathadder Chroma) gets the chroma effects, but the k95 stays the same.

I noticed that the .dll file in DOOM is called **"CChromaEditorLibrary.dll"**, when I copy the dlls to the doom folder, my mouse stops displaying the effect and the keyboard stays the same.

Is there anything I can do to enable DOOM support?

Regards,
Pedro Brito

**Comment by MartB** [comment]
I will take a look at it, might be only a second set of dll function exports needed from my app.
No promises though!

**Comment by MartB** [comment]
Okay i think i got it fixed (i dont own the game though so you need to test it for me)

Try https://github.com/MartB/RETC/releases/tag/v3.2.7 and see if it works now.
(You need to copy the dlls again)

**Comment by PR91** [comment]
It works flawlessly now! Thank You! I can see what chroma optimized games I own, and report what works and what doesn't if you want.

**Comment by MartB** [comment]
Glad to hear!
If it uses any of these two dlls chances are its supported.
(If you find some oddities create a separate issue)

Thanks for testing.
