### ISSUE TITLE
Corsair Headset Stand Won't work

### ISSUE THREAD

**Issue by PixelSquish** [MartB/RETC#23]
great program - anyway to add the corsair headset stand into the mix here?

**Comment by MartB** [comment]
If razer had one it would be trivial, but for now i might be able to clone the headset / mousepad leds and apply them to the stand. (It does have 9 zones right?)

**Comment by MartB** [comment]
@PixelSquish this should now be supported.
Its not perfect but i did not find a better way to map 9 led zones from corsair to 15 on razer.

Tell me if it works fine for you!

**Comment by MartB** [comment]
#closed this is now implemented

@PixelSquish if you ever get around to test this feel free to reply!
