### ISSUE TITLE
Corsair Glaive Support

### ISSUE THREAD

**Issue by chefuu** [MartB/RETC#24]
Seems to be missing support for the Corsair Glaive RGB

**Comment by MartB** [comment]
This device was not supported by the official corsair SDK when i last checked, will probably take a look at this when my exams are over.

**Comment by MartB** [comment]
I did take a look and it needs an ugly workaround but it should work now (the demo device inside iCue does atleast).

Download the new version and give it a try ~~when i publish it~~.

New version is out: https://github.com/MartB/RETC/releases/tag/v3.4
