### ISSUE TITLE
Corsair Dark Core RGB Support

### ISSUE THREAD

**Issue by robfrizzy** [MartB/RETC#25]
What's the possibility of adding support for the Dark Core RGB?

**Comment by MartB** [comment]
According to http://forum.corsair.com/v3/showthread.php?t=179027 it does not seem to be supported by the corsair sdk (yet).

When i update the corsair sdk you could give it a try, but as its not officially listed i cant guarantee anything.

**Comment by robfrizzy** [comment]
Sorry for the late response. I was actually just playing Far Cry: New Dawn. It has native iCue support and changes the RGB lighting in response to the game. My Dark Core definitely changed along with my other peripherals. Is this the same as having SDK support? Granted, I haven’t tried any Chroma games in a while to see if it works with them yet or not.

**Comment by MartB** [comment]
Thanks for this pointer, i will investigate and publish a test version here.

**Comment by MartB** [comment]
Can you re-test with the ~~soon to be released~~ new version?

New version is out: https://github.com/MartB/RETC/releases/tag/v3.4
