### ISSUE TITLE
Persistent effects are not played

### ISSUE THREAD

**Issue by jyrkive** [MartB/RETC#26]
https://github.com/MartB/RETC/blob/74fa8c3ded4775ef9079bfdd6939a71aef0a5c1c/server-exe/SDKManager.cpp#L156-L160

If we enter the if block, the effect is stored via `EffectManager::storeEffect()`, and then we immediately return without playing the effect (note that line 157 begins with `return`). `storeEffect()` doesn't seem to implicitly play the effect, neither immediately nor later.

I'm not contributing a fix at this time because I can't tell how the code is intended to work.

**Comment by MartB** [comment]
Iirc this is an razer api thing, if the effect guid is set inside playEffect we are supposed to only save the effect for this guid and not play it until it gets requested later (by SetEffect).

This is how the official razer keyboard api test program expects things to work atleast.

**Comment by MartB** [comment]
Regardless is there any sample that doesnt work like this?

**Comment by jyrkive** [comment]
Yeah, the Vivaldi web browser that [just got Razer Chroma integration in the latest update](https://vivaldi.com/blog/vivaldi-browser-enables-razer-chroma/).

Interesting to hear that apparently it's Vivaldi that uses the API incorrectly...

**Comment by MartB** [comment]
Vivaldi uses the api in the following way,
```
CreateKeyboardEffect type, CHROMA_STATIC (4) guid: 0x008feb04 {0F9B4E2F-9F4A-0C9B-BD7E-5D4B85BD8C5E}
CreateKeyboardEffect type, CHROMA_STATIC (4) guid: 0x008feb04 {9BA1C0EF-D917-454C-9E9A-46E4AB337824}
CreateKeyboardEffect type, CHROMA_STATIC (4) guid: 0x008feb04 {723F73D8-6FB8-4176-94F4-34C70A82B5E4}
CreateKeyboardEffect type, CHROMA_STATIC (4) guid: 0x008feb04 {6AB75F46-E39A-4F46-95AE-058025C0E5F6}
CreateKeyboardEffect type, CHROMA_STATIC (4) guid: 0x008feb04 {7E82C073-3798-466C-914E-1C4C68FFFCC1}
CreateKeyboardEffect type, CHROMA_STATIC (4) guid: 0x008feb04 {4E9A88A1-CD96-4A39-BCC0-F1A159F41957}
CreateKeyboardEffect type, CHROMA_STATIC (4) guid: 0x008feb04 {E30FFAA1-2F67-482C-A30E-438CD557AD2D}
CreateKeyboardEffect type, CHROMA_STATIC (4) guid: 0x008feb04 {8D354EE2-9FCE-40CC-A04B-8D20B9E6A4DA}
CreateKeyboardEffect type, CHROMA_STATIC (4) guid: 0x008feb04 {2B770EC5-76E5-47F1-9A23-A8B9D89ABC31}
CreateKeyboardEffect type, CHROMA_STATIC (4) guid: 0x008feb04 {7E3E4C46-DBE0-4A4C-937D-3A15C75B5CEC}
CreateKeyboardEffect type, CHROMA_STATIC (4) guid: 0x008feb04 {0F9B4E2F-A12F-E7E9-ADE6-6343BD3D5433}
CreateKeyboardEffect type, CHROMA_STATIC (4) guid: 0x008feb04 {2E16CC2F-CC24-418F-AB87-1A7C286A4D81}
CreateKeyboardEffect type, CHROMA_STATIC (4) guid: 0x008feb04 {ADC43B28-88E2-49A3-A00C-AB99FEE1B334}
CreateKeyboardEffect type, CHROMA_STATIC (4) guid: 0x008feb04 {3BDD43FA-FFE4-43D5-96F3-D593A252E847}
CreateKeyboardEffect type, CHROMA_STATIC (4) guid: 0x008feb04 {7483DDCC-D3FE-4576-A215-9697BEA5BEF7}
CreateKeyboardEffect type, CHROMA_STATIC (4) guid: 0x008feb04 {80CDF540-144E-4301-AC8B-315023DDEE97}
CreateKeyboardEffect type, CHROMA_STATIC (4) guid: 0x008feb04 {F1EBBF3E-1763-48D8-864C-7A7DA9AD5128}
CreateKeyboardEffect type, CHROMA_STATIC (4) guid: 0x008feb04 {2913E69F-5022-4EF3-9BD0-A15B5E7FD2AC}
CreateKeyboardEffect type, CHROMA_STATIC (4) guid: 0x008feb04 {27B8FA33-7BDA-46A3-A7D6-768C5A93B181}
CreateKeyboardEffect type, CHROMA_STATIC (4) guid: 0x008feb04 {B2594F61-7135-47D7-A025-4BDF31BF6503}
```

The guid does not exist in our effect store though, so im not quite sure what to do with it, as the razer api docs lack any sort of documentation for whats supposed to happen if a non null guid is passed to CreateKeyboardEffect. 

The sample on razers page does it different (correct?!) https://assets.razerzone.com/dev_portal/docs/_chroma_s_d_k_impl_8cpp-example.html
It does save the effects supplying a 0-Guid and expects them to get saved instead of played.

From my point of view, it looks like Razer is failing gracefully in vivaldis case, or i am missing an important decision in razers api code.

A fix for this could look sth like this:
```c++
// We got a valid effectID, pointer
if (pEffectId != nullptr) {
	const auto guid = *pEffectId;
	// The user supplied a NULL guid, try to give him a new valid one and store the effect.
	if (guid == GUID_NULL) {
		return m_effectManager->storeEffect(devType, effectType, pEffectId, size, effectData) ? RZRESULT_SUCCESS : RZRESULT_FAILED;
	}

	// [API Not clear] The Effect might exist already, as the supplied guid was not null, if not playback directly
	// Note: This could also be only playbackEffect, but at this stage im not sure.
	return setEffect(guid) != RZRESULT_NOT_FOUND || playbackEffect(devType, effectType, effectData);
}
```

However im not sure if the setEffect branch is valid or only playbackEffect should be used here.

**Comment by MartB** [comment]
I went ahead and prepared a test setup for you, which should theoretically work
Its based on https://github.com/MartB/RETC/commit/27a64e93d509c2412e18ede5dc513cece187bc70

[RETC_Setup.zip](https://github.com/MartB/RETC/files/3172146/RETC_Setup.zip)

Can you report back if everything works correctly for you?

**Comment by jyrkive** [comment]
Yes, I can confirm that it works on my system (with Corsair K95 RGB Platinum keyboard). 👍
