### ISSUE TITLE
Some effect is missing with Overwatch game.

### ISSUE THREAD

**Issue by Jaazzy** [MartB/RETC#8]
Hi @MartB since u have update RETC Server some effect who are missing before is now available , i expect some effect is missing and i want to know why?

And what is "RazerPassthrough"?

Thanks you

**Comment by MartB** [comment]
Sorry i dont think i got the first part of your question is there something missing? 
Razer Passthrough allows you to still use the rgb lighting of your razer devices so you can run setups like the following
Razer Mouse Corsair keyboard
Razer Headset Corsair Mouse Razer Keyboard etc. 
Only a few examples.

**Comment by Jaazzy** [comment]
For exemple , with the first version of RETC Junkrat have no effect on his ultimate
but now with the last RETC the effect on junkrat ultimate is available.

**Comment by MartB** [comment]
Interesting i guess blizzard added that to the game then.
My project has no game specific effects everything you see was done with the razer api from within overwatch.

**Comment by Jaazzy** [comment]
No i mean yesterday the ultimate effect on Junkrat doesn't work but now when i launch the new retc_server you have release i got a ultimate effect on junkrat.

**Comment by MartB** [comment]
I did not really change a thing related to effect processing besides the fn key though. Im still thinking that was Blizzard adding/fixing that effect. Eitherway everything seems to be alright i will close this issue if you don't have any related questions anymore.

**Comment by Jaazzy** [comment]
Alright thanks you for answer.
